### ISSUE TITLE
Unable to remove failed kube

### ISSUE THREAD

**Issue by jordanrinke** [supergiant/supergiant#217] opened 2017-06-14 00:03 UTC
In testing, if a kube is provisioned but fails for any reason (such as, an invalid image name/type in the OpenStack driver) a kube resource is created in SG but there is no way to remove it (via the UI at least). Attempting to delete it, gives a resource not found error and the UI is left with a kube listed in the "failed" state with no way to correct it.

**Comment by gopherstein** [comment] 2018-03-23 17:46
So we have gone through and fixed delete hangups from failed Kubes... but the problem is not universal. Meaning there may be other "hangups" that can cause this to happen. We have created a bypass process that will force delete if it finds that the API says certain resources do not exist. If we see this again in the future we need to document the exact log hangups the reoccurring service is erroring about and we can add those to our bypass process.

**Comment by gopherstein** [comment] 2018-03-23 17:47
Forgot to mention it in the pull comment, but the fix is in this pull (will add it)https://github.com/supergiant/supergiant/pull/452

**Closed** 2018-03-23 17:48 UTC
Labels: 1.0.0, bug
