### ISSUE TITLE
1.0: If a node is on "NotReady" status Supergiant won't spin a new node

### ISSUE THREAD

**Issue by alterx** [supergiant/supergiant#369] opened 2017-10-24 15:57 UTC
Provider: AWS
Kubernetes version: 1.6.7
Supergiant version: 0.15.6

We had an issue and one of our nodes filled up. This caused the docker daemon to die hence making the node status "NotReady". This happened over the weekend and there were several pending pods that were never started. I even tried to manually schedule pods to see if Supergiant would spin a new node but after some time waiting I gave up: it looks like under these circumstances SG won't spin a new node.

One thing that may or may not have anything to do with this issue but I think makes sense to mention is that the node that filled up was the initial node (the one that's added alongside the master when you create a new kube)

**Comment by TheKLARKEN** [comment] 2018-03-16 16:51
Hi, @alterx, do you think I could work with you sometime to figure out how to reproduce this error?

**Comment by gopherstein** [comment] 2018-11-20 17:30
Closing due to age and response.

**Closed by gopherstein** 2018-11-20 17:30 UTC
Labels: bug
