### ISSUE TITLE
2.0: DO provisioning can randomly fail

### ISSUE THREAD

**Issue by eldridgeh** [supergiant/supergiant#786] opened 2018-11-08 21:53 UTC
Summary of Issue:
When spinning up a DO cluster, nodes can randomly fail.

Steps to Reproduce:
1. Spin up a DO cluster

Expected Results:
Clusters spin up without issue.

Actual Results:
Node provisioning randomly fails. You get the attached error in the SG logs. 

Dev Info: (fill out and add links to log files)
1. `go version`: 1.10
2. SG latest commit hash or release tag: dddedff38267d34e16763fde1955ca4dec1cc5d7
3. Number of Masters and Nodes: Any
4. cloud provider: DO
[do_issue.log](https://github.com/supergiant/supergiant/files/2563738/do_issue.log)

**Comment by gopherstein** [comment] 2018-11-13 20:48
Seems to be resolved by another pull. If this continues please re-open. We also need more specific reproduction notes.

**Closed by gopherstein** 2018-11-13 20:48 UTC
