### ISSUE TITLE
2.0: API - AWS metrics being returned as private IP instead of node name

### ISSUE THREAD

**Issue by gopherstein** [supergiant/supergiant#882] opened 2018-11-14 19:56 UTC
![Screen Shot 2018-11-14 at 7:56 PM](http://marker.screenshots.prod.s3.amazonaws.com/7bd5d378f6844e31ac709416680590d2-1542225385268.png)
---
### More Info
AWS metrics for the table in the clusters detail age is being returned as the privateIP and not as the box's name. Due to this, cluster metrics are not showing up in the table for this provider. The inline metrics in the table on the details page for AWS needs to be returned as the node's name.

What AWS is returning this:
![screen shot 2018-11-14 at 1 58 21 pm](https://user-images.githubusercontent.com/35240784/48509154-e47aa400-e815-11e8-8687-797681acbb1b.png)

Here is an example of what DO is returned as:
![screen shot 2018-11-14 at 1 59 38 pm](https://user-images.githubusercontent.com/35240784/48509178-f78d7400-e815-11e8-8e5f-a28faf480196.png)

**Reported by:** eldridge henley (eldridge@qbox.io)
**Source URL**: [http://localhost:4200/clusters/46f8efd7](http://localhost:4200/clusters/46f8efd7)

<table><tr><td><strong>Browser</strong></td><td>Chrome 70.0.3538.77</td></tr><tr><td><strong>Screen Size</strong></td><td>1920 x 1080</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.1</td></tr><tr><td><strong>Viewport Size</strong></td><td>1831 x 1027</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@1x</td></tr></table>

**Comment by eldridgeh** [comment] 2018-11-14 20:49
@stgleb 
This is a duplicate of #861 
I am resolving 861 as this issue has more info in it.

**Closed** 2018-11-20 20:22 UTC
Labels: High Priority
