### ISSUE TITLE
2.0: AWS - Inline metrics not coming through

### ISSUE THREAD

**Issue by gopherstein** [supergiant/supergiant#861] opened 2018-11-13 17:52 UTC
![Screen Shot 2018-11-13 at 5:52 PM](http://marker.screenshots.prod.s3.amazonaws.com/44344ccc33ea4f25abf409f4e02ad4f3-1542131562059.png)
---
### More Info

**Reported by:** eldridge henley (eldridge@qbox.io)
**Source URL**: [http://localhost:4200/clusters/lebowski-1](http://localhost:4200/clusters/lebowski-1)

<table><tr><td><strong>Browser</strong></td><td>Chrome 70.0.3538.77</td></tr><tr><td><strong>Screen Size</strong></td><td>1680 x 1050</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.1</td></tr><tr><td><strong>Viewport Size</strong></td><td>1334 x 1027</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@2x</td></tr></table>

**Comment by eldridgeh** [comment] 2018-11-14 20:53
duplicate of #882, please re-open if needed.

**Closed by eldridgeh** 2018-11-14 20:53 UTC
Labels: High Priority
