### ISSUE TITLE
2.0: UI - Short IP addresses malform the Machines table on the details page.

### ISSUE THREAD

**Issue by gopherstein** [supergiant/supergiant#902] opened 2018-11-15 20:15 UTC
![Screen Shot 2018-11-15 at 8:15 PM](http://marker.screenshots.prod.s3.amazonaws.com/d38e3782b53f4cc3a11bace74f72a56f-1542312951479.png)
---
### More Info

**Reported by:** eldridge henley (eldridge@qbox.io)
**Source URL**: [http://localhost:4200/clusters/d6dad514](http://localhost:4200/clusters/d6dad514)

<table><tr><td><strong>Browser</strong></td><td>Chrome 70.0.3538.77</td></tr><tr><td><strong>Screen Size</strong></td><td>1680 x 1050</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.1</td></tr><tr><td><strong>Viewport Size</strong></td><td>1488 x 1027</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@2x</td></tr></table>

**Comment by josephkane** [comment] 2018-11-17 15:31
Partial duplicate of https://github.com/supergiant/supergiant/issues/914, closing

**Closed by josephkane** 2018-11-17 15:31 UTC
Labels: Low Priority
